apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "contextops" }}
  labels:
    name: {{ .Values.namespace | default "contextops" }}
    app.kubernetes.io/name: contextops
    app.kubernetes.io/part-of: contextops-platform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "contextops.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
  {{- if .Values.namespaceLabels }}
  {{- toYaml .Values.namespaceLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.namespaceAnnotations }}
  annotations:
  {{- toYaml .Values.namespaceAnnotations | nindent 4 }}
  {{- end }}