package gitops

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1"
	argoclientset "github.com/argoproj/argo-cd/v2/pkg/client/clientset/versioned"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
)

// ApplicationSetCorrelator manages ArgoCD ApplicationSet monitoring and correlation
type ApplicationSetCorrelator struct {
	argoClient argoclientset.Interface
	namespace  string
}

// NewApplicationSetCorrelator creates a new ApplicationSet correlator
func NewApplicationSetCorrelator(argoClient argoclientset.Interface, namespace string) *ApplicationSetCorrelator {
	return &ApplicationSetCorrelator{
		argoClient: argoClient,
		namespace:  namespace,
	}
}

// ApplicationSetStatus represents the status of an ApplicationSet
type ApplicationSetStatus struct {
	Name              string                    `json:"name"`
	Namespace         string                    `json:"namespace"`
	Status            string                    `json:"status"` // healthy, progressing, degraded, suspended
	Health            string                    `json:"health"` // healthy, progressing, degraded, missing
	LastSyncTime      *time.Time                `json:"last_sync_time,omitempty"`
	Conditions        []ApplicationSetCondition `json:"conditions"`
	ApplicationsCount int                       `json:"applications_count"`
	Applications      []ApplicationInfo         `json:"applications"`
	Generator         GeneratorStatus           `json:"generator"`
	Template          TemplateStatus            `json:"template"`
	CreatedAt         time.Time                 `json:"created_at"`
	UpdatedAt         time.Time                 `json:"updated_at"`
}

// ApplicationSetCondition represents a condition of an ApplicationSet
type ApplicationSetCondition struct {
	Type               string    `json:"type"`
	Status             string    `json:"status"`
	LastTransitionTime time.Time `json:"last_transition_time"`
	Reason             string    `json:"reason"`
	Message            string    `json:"message"`
}

// ApplicationInfo represents information about an Application generated by an ApplicationSet
type ApplicationInfo struct {
	Name         string     `json:"name"`
	Namespace    string     `json:"namespace"`
	Status       string     `json:"status"`
	Health       string     `json:"health"`
	SyncStatus   string     `json:"sync_status"`
	LastSyncTime *time.Time `json:"last_sync_time,omitempty"`
	Environment  string     `json:"environment,omitempty"`
	Cluster      string     `json:"cluster,omitempty"`
}

// GeneratorStatus represents the status of an ApplicationSet generator
type GeneratorStatus struct {
	Type       string                 `json:"type"`   // git, clusters, list
	Status     string                 `json:"status"` // active, error, inactive
	Parameters map[string]interface{} `json:"parameters"`
	LastUpdate time.Time              `json:"last_update"`
	ErrorCount int                    `json:"error_count"`
}

// TemplateStatus represents the status of an ApplicationSet template
type TemplateStatus struct {
	SourceRepoURL    string    `json:"source_repo_url"`
	SourcePath       string    `json:"source_path"`
	TargetRevision   string    `json:"target_revision"`
	LastValidation   time.Time `json:"last_validation"`
	ValidationStatus string    `json:"validation_status"` // valid, invalid, unknown
}

// GetApplicationSetStatus retrieves the status of a specific ApplicationSet
func (asc *ApplicationSetCorrelator) GetApplicationSetStatus(ctx context.Context, name string) (*ApplicationSetStatus, error) {
	appSet, err := asc.argoClient.ArgoprojV1alpha1().ApplicationSets(asc.namespace).Get(ctx, name, metav1.GetOptions{})
	if err != nil {
		return nil, fmt.Errorf("failed to get ApplicationSet %s: %w", name, err)
	}

	return asc.buildApplicationSetStatus(ctx, appSet)
}

// ListApplicationSetStatuses retrieves the status of all ApplicationSets with optional label selector
func (asc *ApplicationSetCorrelator) ListApplicationSetStatuses(ctx context.Context, labelSelector string) ([]*ApplicationSetStatus, error) {
	listOptions := metav1.ListOptions{}
	if labelSelector != "" {
		listOptions.LabelSelector = labelSelector
	}

	appSets, err := asc.argoClient.ArgoprojV1alpha1().ApplicationSets(asc.namespace).List(ctx, listOptions)
	if err != nil {
		return nil, fmt.Errorf("failed to list ApplicationSets: %w", err)
	}

	var statuses []*ApplicationSetStatus
	for _, appSet := range appSets.Items {
		status, err := asc.buildApplicationSetStatus(ctx, &appSet)
		if err != nil {
			// Log error but continue processing other ApplicationSets
			continue
		}
		statuses = append(statuses, status)
	}

	return statuses, nil
}

// GetApplicationSetsByCustomer retrieves ApplicationSets for a specific customer
func (asc *ApplicationSetCorrelator) GetApplicationSetsByCustomer(ctx context.Context, customerID string) ([]*ApplicationSetStatus, error) {
	labelSelector := fmt.Sprintf("platformctl.io/customer=%s", customerID)
	return asc.ListApplicationSetStatuses(ctx, labelSelector)
}

// GetApplicationSetsByContext retrieves ApplicationSets for a specific context
func (asc *ApplicationSetCorrelator) GetApplicationSetsByContext(ctx context.Context, contextName, customerID string) ([]*ApplicationSetStatus, error) {
	labelSelector := fmt.Sprintf("platformctl.io/customer=%s,platformctl.io/context=%s", customerID, contextName)
	return asc.ListApplicationSetStatuses(ctx, labelSelector)
}

// buildApplicationSetStatus builds ApplicationSetStatus from ArgoCD ApplicationSet
func (asc *ApplicationSetCorrelator) buildApplicationSetStatus(ctx context.Context, appSet *v1alpha1.ApplicationSet) (*ApplicationSetStatus, error) {
	status := &ApplicationSetStatus{
		Name:      appSet.Name,
		Namespace: appSet.Namespace,
		Status:    asc.determineApplicationSetStatus(appSet),
		Health:    asc.determineApplicationSetHealth(appSet),
		CreatedAt: appSet.CreationTimestamp.Time,
		UpdatedAt: time.Now(),
	}

	// Extract conditions
	for _, condition := range appSet.Status.Conditions {
		status.Conditions = append(status.Conditions, ApplicationSetCondition{
			Type:               string(condition.Type),
			Status:             string(condition.Status),
			LastTransitionTime: condition.LastTransitionTime.Time,
			Reason:             condition.Reason,
			Message:            condition.Message,
		})
	}

	// Get generated Applications
	applications, err := asc.getGeneratedApplications(ctx, appSet)
	if err != nil {
		return nil, fmt.Errorf("failed to get generated applications: %w", err)
	}

	status.Applications = applications
	status.ApplicationsCount = len(applications)

	// Build generator status
	status.Generator = asc.buildGeneratorStatus(appSet)

	// Build template status
	status.Template = asc.buildTemplateStatus(appSet)

	return status, nil
}

// determineApplicationSetStatus determines the overall status of an ApplicationSet
func (asc *ApplicationSetCorrelator) determineApplicationSetStatus(appSet *v1alpha1.ApplicationSet) string {
	// Check conditions for error states
	for _, condition := range appSet.Status.Conditions {
		if condition.Type == "ErrorOccurred" && condition.Status == v1alpha1.ApplicationSetConditionStatusTrue {
			return "degraded"
		}
		if condition.Type == "ResourcesUpToDate" && condition.Status == v1alpha1.ApplicationSetConditionStatusFalse {
			return "progressing"
		}
	}

	// Check if ApplicationSet is suspended
	if appSet.Spec.SyncPolicy != nil && appSet.Spec.SyncPolicy.PreserveResourcesOnDeletion {
		return "suspended"
	}

	return "healthy"
}

// determineApplicationSetHealth determines the health of an ApplicationSet
func (asc *ApplicationSetCorrelator) determineApplicationSetHealth(appSet *v1alpha1.ApplicationSet) string {
	// Simple health determination based on conditions
	hasErrorCondition := false
	for _, condition := range appSet.Status.Conditions {
		if strings.Contains(strings.ToLower(string(condition.Type)), "error") && condition.Status == v1alpha1.ApplicationSetConditionStatusTrue {
			hasErrorCondition = true
			break
		}
	}

	if hasErrorCondition {
		return "degraded"
	}

	if len(appSet.Status.Conditions) == 0 {
		return "missing"
	}

	return "healthy"
}

// getGeneratedApplications retrieves all Applications generated by an ApplicationSet
func (asc *ApplicationSetCorrelator) getGeneratedApplications(ctx context.Context, appSet *v1alpha1.ApplicationSet) ([]ApplicationInfo, error) {
	// List Applications with owner reference to this ApplicationSet
	labelSelector := labels.SelectorFromSet(labels.Set{
		"argocd.argoproj.io/application-set-name": appSet.Name,
	})

	apps, err := asc.argoClient.ArgoprojV1alpha1().Applications(asc.namespace).List(ctx, metav1.ListOptions{
		LabelSelector: labelSelector.String(),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list applications for ApplicationSet %s: %w", appSet.Name, err)
	}

	var applications []ApplicationInfo
	for _, app := range apps.Items {
		appInfo := ApplicationInfo{
			Name:       app.Name,
			Namespace:  app.Namespace,
			Status:     asc.determineApplicationStatus(&app),
			Health:     asc.determineApplicationHealth(&app),
			SyncStatus: string(app.Status.Sync.Status),
		}

		// Extract environment and cluster information from labels or annotations
		if env, ok := app.Labels["platformctl.io/environment"]; ok {
			appInfo.Environment = env
		}
		if cluster, ok := app.Labels["platformctl.io/cluster"]; ok {
			appInfo.Cluster = cluster
		}

		// Get last sync time
		if app.Status.OperationState != nil && app.Status.OperationState.FinishedAt != nil {
			appInfo.LastSyncTime = &app.Status.OperationState.FinishedAt.Time
		}

		applications = append(applications, appInfo)
	}

	return applications, nil
}

// determineApplicationStatus determines the status of an Application
func (asc *ApplicationSetCorrelator) determineApplicationStatus(app *v1alpha1.Application) string {
	if app.Status.Health.Status != "" {
		return string(app.Status.Health.Status)
	}
	return "unknown"
}

// determineApplicationHealth determines the health of an Application
func (asc *ApplicationSetCorrelator) determineApplicationHealth(app *v1alpha1.Application) string {
	if app.Status.Health.Status != "" {
		return string(app.Status.Health.Status)
	}
	return "unknown"
}

// buildGeneratorStatus builds generator status from ApplicationSet spec
func (asc *ApplicationSetCorrelator) buildGeneratorStatus(appSet *v1alpha1.ApplicationSet) GeneratorStatus {
	status := GeneratorStatus{
		Type:       "unknown",
		Status:     "active",
		Parameters: make(map[string]interface{}),
		LastUpdate: time.Now(),
	}

	// Determine generator type and extract parameters
	if len(appSet.Spec.Generators) > 0 {
		generator := appSet.Spec.Generators[0]

		if generator.Git != nil {
			status.Type = "git"
			status.Parameters["repoURL"] = generator.Git.RepoURL
			status.Parameters["revision"] = generator.Git.Revision
			if len(generator.Git.Directories) > 0 {
				status.Parameters["directories"] = generator.Git.Directories
			}
			if len(generator.Git.Files) > 0 {
				status.Parameters["files"] = generator.Git.Files
			}
		} else if generator.Clusters != nil {
			status.Type = "clusters"
			status.Parameters["selector"] = generator.Clusters.Selector
		} else if generator.List != nil {
			status.Type = "list"
			status.Parameters["elements"] = generator.List.Elements
		}
	}

	return status
}

// buildTemplateStatus builds template status from ApplicationSet spec
func (asc *ApplicationSetCorrelator) buildTemplateStatus(appSet *v1alpha1.ApplicationSet) TemplateStatus {
	status := TemplateStatus{
		LastValidation:   time.Now(),
		ValidationStatus: "valid",
	}

	// Extract source information from template
	if appSet.Spec.Template.Spec.Source != nil {
		status.SourceRepoURL = appSet.Spec.Template.Spec.Source.RepoURL
		status.SourcePath = appSet.Spec.Template.Spec.Source.Path
		status.TargetRevision = appSet.Spec.Template.Spec.Source.TargetRevision
	}

	return status
}

// MonitorApplicationSetHealth monitors the health of ApplicationSets and returns any that are unhealthy
func (asc *ApplicationSetCorrelator) MonitorApplicationSetHealth(ctx context.Context, customerID string) ([]*ApplicationSetStatus, error) {
	allStatuses, err := asc.GetApplicationSetsByCustomer(ctx, customerID)
	if err != nil {
		return nil, fmt.Errorf("failed to get ApplicationSets for customer %s: %w", customerID, err)
	}

	var unhealthyStatuses []*ApplicationSetStatus
	for _, status := range allStatuses {
		if status.Status == "degraded" || status.Health == "degraded" || status.Health == "missing" {
			unhealthyStatuses = append(unhealthyStatuses, status)
		}
	}

	return unhealthyStatuses, nil
}

// GetApplicationSetMetrics returns metrics about ApplicationSet performance
func (asc *ApplicationSetCorrelator) GetApplicationSetMetrics(ctx context.Context, name string) (*ApplicationSetMetrics, error) {
	status, err := asc.GetApplicationSetStatus(ctx, name)
	if err != nil {
		return nil, err
	}

	metrics := &ApplicationSetMetrics{
		Name:                  name,
		TotalApplications:     status.ApplicationsCount,
		HealthyApplications:   0,
		UnhealthyApplications: 0,
		SyncedApplications:    0,
		OutOfSyncApplications: 0,
		LastUpdateTime:        status.UpdatedAt,
	}

	for _, app := range status.Applications {
		if app.Health == "healthy" {
			metrics.HealthyApplications++
		} else {
			metrics.UnhealthyApplications++
		}

		if app.SyncStatus == "Synced" {
			metrics.SyncedApplications++
		} else {
			metrics.OutOfSyncApplications++
		}
	}

	return metrics, nil
}

// ApplicationSetMetrics represents metrics for an ApplicationSet
type ApplicationSetMetrics struct {
	Name                  string    `json:"name"`
	TotalApplications     int       `json:"total_applications"`
	HealthyApplications   int       `json:"healthy_applications"`
	UnhealthyApplications int       `json:"unhealthy_applications"`
	SyncedApplications    int       `json:"synced_applications"`
	OutOfSyncApplications int       `json:"out_of_sync_applications"`
	LastUpdateTime        time.Time `json:"last_update_time"`
}
