#!/bin/bash

# ContextOps API Test Commands for Monitoring the ApplicationSet
# Run these commands to test ContextOps monitoring capabilities

echo "=== ContextOps ApplicationSet Monitoring Test Commands ==="
echo ""

GATEWAY_URL="http://contextops-gateway"
CUSTOMER="acme-corp"

echo "1. Query GitOps Status for the customer:"
echo "kubectl exec -n contextops deployment/contextops-gateway -- curl -s -u admin:admin \"$GATEWAY_URL/api/v1/gitops/status?customer_id=$CUSTOMER\""
echo ""

echo "2. Query ApplicationSets being monitored:"
echo "kubectl exec -n contextops deployment/contextops-gateway -- curl -s -u admin:admin \"$GATEWAY_URL/api/v1/gitops/applicationsets?customer_id=$CUSTOMER\""
echo ""

echo "3. Query Applications generated by ApplicationSets:"
echo "kubectl exec -n contextops deployment/contextops-gateway -- curl -s -u admin:admin \"$GATEWAY_URL/api/v1/gitops/applications?customer_id=$CUSTOMER\""
echo ""

echo "4. Query specific context (application-environment pairing):"
echo "kubectl exec -n contextops deployment/contextops-gateway -- curl -s -u admin:admin \"$GATEWAY_URL/api/v1/contexts/demo-app-dev?customer_id=$CUSTOMER\""
echo ""

echo "5. Trigger ApplicationSet sync action:"
echo "kubectl exec -n contextops deployment/contextops-gateway -- curl -s -u admin:admin -X POST \"$GATEWAY_URL/api/v1/contexts/demo-app-dev/actions/sync-apps?customer_id=$CUSTOMER\""
echo ""

echo "6. Validate environment configurations:"
echo "kubectl exec -n contextops deployment/contextops-gateway -- curl -s -u admin:admin -X POST \"$GATEWAY_URL/api/v1/contexts/demo-app-prod/actions/validate-environments?customer_id=$CUSTOMER\""
echo ""

echo "=== Direct ArgoCD API Queries (from within cluster) ==="
echo ""

ARGOCD_SERVER="http://contextops-argocd-server"

echo "7. Direct ArgoCD ApplicationSet query:"
echo "kubectl exec -n contextops deployment/contextops-gateway -- curl -s \"$ARGOCD_SERVER/api/v1/applicationsets\""
echo ""

echo "8. Direct ArgoCD Applications query:"
echo "kubectl exec -n contextops deployment/contextops-gateway -- curl -s \"$ARGOCD_SERVER/api/v1/applications\""
echo ""

echo "9. Query specific Application status:"
echo "kubectl exec -n contextops deployment/contextops-gateway -- curl -s \"$ARGOCD_SERVER/api/v1/applications/demo-app-dev\""
echo ""

echo "=== Test Application Details ==="
echo ""
echo "ApplicationSet Name: contextops-demo-apps"
echo "Generated Applications:"
echo "  - demo-app-dev (development environment, 1 replica, develop branch)"
echo "  - demo-app-qa (QA environment, 1 replica, main branch)"  
echo "  - demo-app-prod (production environment, 2 replicas, main branch)"
echo ""
echo "Customer Labels: contextops.io/customer=acme-corp"
echo "Monitoring Labels: contextops.io/monitored=true"
echo "Environment Labels: contextops.io/environment=dev/qa/prod"
echo ""