{{- if .Values.rbac.create }}
{{- range $sa := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa }}
  labels:
    {{- include "platformctl.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $sa }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
